### PR TITLE
feat(node): integrate Sentry for automated bug reporting / telemetry

### LINKED ISSUE #1177: Add support for Sentry so users can voluntarily provide debug traces
Integrating Sentry would give us the opportunity to collect debug traces from users while on Testnet stage.

### PR DESCRIPTION
**Pull request by aesedepece**
This feature is disabled by default, but currently enabled by the `witnet.toml` configuration file.

Fix #1177

### CODE REVIEW

File: src/cli/mod.rs [hunk 1]
```diff
@@ -75,7 +78,28 @@ fn init_logger(opts: LogOptions) {
...
         .filter_level(log::LevelFilter::Info)
         .filter_module("witnet", opts.level)
-        .init();
+        .filter_module("witnet_node", opts.level);
+
+    // Initialize Sentry (automated bug reporting) if explicitly enabled in configuration
+    if opts.sentry_telemetry {
+        // Initialize client
+        let guard = sentry::init(
+            "https://def0c5d0fb354ef9ad6dddb576a21624@o394464.ingest.sentry.io/5244595",
```
Comment (tmpolaczyk) [inline src/cli/mod.rs:87]: Would it make sense to be able to change this URL in witnet.toml?

File: Cargo.toml [hunk 2]
```diff
@@ -34,6 +34,7 @@ itertools = "0.8.2"
 lazy_static = "1.4.0"
 log = "0.4.8"
 prettytable-rs = { version = "0.8.0", default-features = false }
+sentry = { version = "0.18.1", features = ["with_env_logger"] }
```
Comment (tmpolaczyk) [inline Cargo.toml:37]: Can we make this dependency optional so that people can still compile the node without any telemetry? Although I don't know what's the command to disable some feature when compiling.

```suggestion
sentry = { version = "0.18.1", features = ["with_env_logger"], optional = true }
```

File: witnet.toml [hunk 3]
```diff
@@ -75,7 +75,10 @@ genesis_path = "genesis_block.json"
 split_mint = true
 
 [log]
+# Logging level, i.e. from more verbose to quieter: "trace" > "debug" > "info" > "warn" > "error" > "nano"
```
Comment (lrubiorod) [inline witnet.toml:78]: Nanoooo!! :P

File: src/cli/mod.rs (hunk 1 above)
Comment (aesedepece) [reply src/cli/mod.rs:87]: Let's postpone the decision until we have validated if Sentry is useful and how long it stays here.
