### PR TITLE
fix(data_structures): update reveal stage on zero reveals

### LINKED ISSUE #945: Fix missing reveals remediation
While creating tally transactions nodes should take into account the `extra_reveal_rounds` parameter in order to avoid DoS from committers.

In case of 0 revealers and the extra reveal rounds are over, the tally should be resolved as `RadonError`.

### PR DESCRIPTION
**Pull request by tmpolaczyk**
Fix #945

### CODE REVIEW

File: rad/src/types/mod.rs [hunk 1]
```diff
@@ -296,6 +296,12 @@ impl TryFrom<&cbor::value::Value> for RadonTypes {
                                                 }
                                             }
                                         }
+                                        RadonErrors::NoReveals => {
+                                            return Err(RadError::NoReveals);
+                                        }
+                                        RadonErrors::Unknown => {
```
Comment (lrubiorod) [inline rad/src/types/mod.rs]: It is not necessary now
