### PR TITLE
Handle bugs produced by empty epochs

### LINKED ISSUE #674: Handle epochs with no block
To ensure correct behavior when an epoch has not consolidated a block, we must:

- [ ] Update `ActiveReputationSet` with an empty vector.
- [ ] Clear commits from `TransactionsPool`.

### LINKED ISSUE #675: Add change in TallyTransaction in case of less reveals than expected
Exist the calculate_tally_change function in data_request.rs to calculate if there are change for the data request creator but it is not used in mining

### PR DESCRIPTION
**Pull request by lrubiorod**
Modified log level of synced state to info
Skipped clippy cognitive_complexity warnings
Updated commits every epoch and reveals every consolidated block
Handled ARS queue in epochs without blocks
Added tally change in tally mining

Close #674 
Close #675

### CODE REVIEW

File: node/src/actors/chain_manager/mod.rs [hunk 1]
```diff
@@ -651,7 +653,7 @@ fn update_reputation(
 
     // Update active reputation set
     // Add block miner pkh to active identities
-    rep_eng.ars.push_activity(revealers.chain(vec![miner_pkh]));
+    rep_eng.update_ars(block_epoch, revealers.chain(vec![miner_pkh]));
```
Comment (tmpolaczyk) [inline node/src/actors/chain_manager/mod.rs]: Since the `ars` is only updated here, it can lead to incorrect results. Consider the case when we are in epoch 100 and there are 40 epochs with no block and the `ars` has a maximum size of 40. The set of active identities should be empty, but it won't be updated until after processing the block for epoch 140. Therefore in the reputation validations for block 140 we will count identities which have participated in epochs 60-99 as active, when clearly they weren't active because in epochs 100-139 there were no blocks.

Comment (lrubiorod) [reply node/src/actors/chain_manager/mod.rs]: It is also updated in ChainManager/handler.rs 138, in case of an empty epoch

File: node/src/actors/chain_manager/handlers.rs [hunk 2]
```diff
@@ -24,6 +24,7 @@ use crate::{
     },
     utils::mode_consensus,
 };
+use witnet_data_structures::chain::ChainState;
```
Comment (tmpolaczyk) [inline node/src/actors/chain_manager/handlers.rs]: Badly formatted import

File: reputation/src/lib.rs [hunk 3]
```diff
@@ -5,10 +5,12 @@
...
-#![deny(missing_docs)]
 
 pub mod trs;
 pub use trs::TotalReputationSet;
 
 pub mod ars;
 pub use ars::ActiveReputationSet;
+
+/// Module containing error definitions
+pub mod error;
```
Comment (tmpolaczyk) [inline reputation/src/lib.rs]: Since you are creating a error module, could you move the errors from `trs.rs` there? (`NonSortedAlpha` and `RepError`)
