### PR TITLE
fix(rad): tell integers from floats when converting from JSON to CBOR

### LINKED ISSUE #1146: Function `json_to_cbor` mistakenly manages all JSON numbers as Float
As seen here, the RAD manager is currently managing all numeric values coming from JSON as `RadonFloat`:
https://github.com/witnet/witnet-rust/blob/2c0e9d614028867ab9c942bcd90c02124693cf2b/rad/src/operators/string.rs#L132

This leads to really poor UX for devs who are expecting those values to be operable using `RadonInteger` operators.

We should detect whether the numeric value has decimals, and cast to `RadonInteger` or `RadonFloat` automatically.

### PR DESCRIPTION
**Pull request by aesedepece**
Fix #1146

### CODE REVIEW

File: rad/src/script.rs [hunk 1]
```diff
@@ -273,14 +276,14 @@ fn test_execute_radon_script() {
             Some(vec![Value::Text(String::from("main"))]),
         ),
         (
-            RadonOpCodes::MapGetFloat,
+            RadonOpCodes::MapGetInteger,
```
Comment (tmpolaczyk) [inline rad/src/script.rs:279]: This is exactly the issue we are trying to solve, now if the temperature changes from -4ºC to -4.5ºC, this data request breaks. So we should find a way to accept both -4 and -4.5 as valid floats, instead of modifying this test to work on integers.

Comment (aesedepece) [reply rad/src/script.rs:279]: If you want that behavior, you can just do `MapGetFloat` instead of `MapGetInteger` and it works as well, I guess. 

Do you prefer if I leave the script in the test just as it was? Maybe the change I made is too reckless and a bad example because it can break easily.

Comment (aesedepece) [reply rad/src/script.rs:279]: I've updated the test to illustrate my point :wink:

Comment (tmpolaczyk) [reply rad/src/script.rs]: I expected the test to not change to make sure we don't break anything. I guess this test was not using `MapGetInteger` because that didn't work, so we also need to add a new test using `MapGetInteger`.

File: rad/src/operators/string.rs [hunk 2]
```diff
@@ -127,7 +130,27 @@ fn json_to_cbor(value: &json::JsonValue) -> Value {
         }
         json::JsonValue::Short(value) => Value::Text(String::from(value.as_str())),
         json::JsonValue::String(value) => Value::Text(String::from(value.as_str())),
-        json::JsonValue::Number(value) => Value::Float((*value).into()),
+        json::JsonValue::Number(value) => {
+            // This trick allows to tell whether a number has decimals by checking whether the
+            // mantissa contains more significant bits than the exponent can express.
```
Comment (tmpolaczyk) [inline rad/src/operators/string.rs:135]: I thought you may be reimplementing `value.as_i64()`, but then I realized we are using `json`, not `serde_json`. No idea why.

https://docs.serde.rs/serde_json/struct.Number.html#method.as_i64

File: rad/src/operators/string.rs [hunk 3]
```diff
@@ -127,7 +130,27 @@ fn json_to_cbor(value: &json::JsonValue) -> Value {
...
+            let (positive, mantissa, exponent) = value.as_parts();
+            // Factor is 10 ^ |exponent|
+            let factor = u64::pow(
+                10,
+                u32::try_from(exponent.abs())
+                    .expect("Exponent of JsonValue::Number should fit in u32"),
+            );
```
Comment (tmpolaczyk) [inline rad/src/operators/string.rs:142]: `u64::pow` will panic if the result does not fit in a u64, for example when the exponent is 100.

File: rad/src/script.rs (hunk 1 above)
Comment (aesedepece) [reply rad/src/script.rs]: Let me see what I can do.

File: rad/src/operators/string.rs (hunk 3 above)
Comment (aesedepece) [reply rad/src/operators/string.rs:142]: Don't think we will ever need 100 as an exponent, because such think doesn't exist in JSON anyway, as it is subject to the limitations of double precision  / binary64 as put forth by IEEE 754 (minimum = `-(2^53 - 1)`, maximum = `2^53 - 1`, exponent_bits = `11`)

Comment (tmpolaczyk) [reply rad/src/operators/string.rs:142]: What do you mean? `1e100` is valid JSON, and `1` followed by 100 zeros is also valid JSON. Add this test:

```rust
        let json = JsonValue::Number(Number::from(1e100));
        let resulting_cbor = json_to_cbor(&json);
        let expected_cbor = serde_cbor::Value::Float(1e100);
        assert_eq!(resulting_cbor, expected_cbor);
```

Comment (aesedepece) [reply rad/src/operators/string.rs]: That works now! :wink:

Comment (tmpolaczyk) [reply rad/src/operators/string.rs]: Cool, let's add a few tests near `i128::MAX` and `i128::MIN` to make sure it works as expected.

**Comment by tmpolaczyk** [comment]
Also we need to make sure that this fixes the issue on sheikah's end. @Tommytrg can you provide an example data request that doesn't work without this PR?

**Comment by aesedepece** [comment]
> Also we need to make sure that this fixes the issue on sheikah's end. @Tommytrg can you provide an example data request that doesn't work without this PR?

Sounds like he can't provide such data request, so I guess this is OK to merge? :stuck_out_tongue:

**Comment by Tommytrg** [comment]
I've been trying this PR whit sheikah and it worked correctly retrieving `integer` and `float`. On the other hand, there is something odd when applying `getFloat` from an integer: it returns the a float wihout decimal. Is this the expected behavior or its out of the scope of this PR?

**Comment by aesedepece** [comment]
> I've been trying this PR whit sheikah and it worked retrieving `integer`s and `float`s. On the other hand, there is something odd when applying `getFloat` from an integer: it returns the a float wihout decimal. Is this the expected behavior or its out of the scope of this PR?

**Comment by aesedepece** [comment]
@witnet/devs anyone against merging this?

**Comment by aesedepece** [comment]
> I've been trying this PR whit sheikah and it worked retrieving `integer`s and `float`s. On the other hand, there is something odd when applying `getFloat` from an integer: it returns the a float wihout decimal. Is this the expected behavior or its out of the scope of this PR?

This is perfectly fine. If it's an integer, you are just expected to do `getInteger`.

**Comment by tmpolaczyk** [comment]
> @witnet/devs anyone against merging this?

imagen

I would just like to see how this PR changes the result of a data request

**Comment by tmpolaczyk** [comment]
> I've been trying this PR whit sheikah and it worked retrieving `integer`s and `float`s. On the other hand, there is something odd when applying `getFloat` from an integer: it returns the a float wihout decimal. Is this the expected behavior or its out of the scope of this PR?

This is because `1.0.to_string()` returns `"1"`. Floats are already annotated so I don't know if adding `.0` will improve UI. Unless we want to always show floats using scientific notation or something, then `1.0` would be `1e0`. But yeah, let's discuss this in a different PR.

**Comment by aesedepece** [comment]
> I would just like to see how this PR changes the result of a data request
Any DR that worked before and stopped working with these changes was malformed anyway because the former implementation of the JSON → CBOR decoder was not conforming to the RADON "standard" :rofl:

**Comment by Tommytrg** [comment]
@tmpolaczyk You can modify a `get` of [this data request](https://github.com/witnet/sheikah/blob/master/examples/subscript.json)  to use `getFloat` or `getIntenger`
