### PR TITLE
fix(mining): fix bug in create_tally function and add tests

### LINKED ISSUE #1117: Tally slashing validations are faulty, thus preventing new blocks from being accepted
## Issue description
There's a subtle mismatch between the business logic being used for creating tally transactions and validating them.

This corner case can be abused to force that new blocks that include tally transactions are rejected by the totality of the network, thus preventing the chain from moving forward.

## Solution
@lrubiorod is working on a solid solution and an additional code test that covers the end-to-end flow of creating a tally transaction and validating it, so as to ensure both processes are consistent.

### PR DESCRIPTION
**Pull request by lrubiorod**
Close #1117

### CODE REVIEW

**Comment by tmpolaczyk** [comment]
Typo in commit name: minint

File: data_structures/src/data_request.rs [hunk 1]
```diff
@@ -400,12 +401,13 @@ where
         }
 
         let tally_bytes = Vec::try_from(report)?;
+        let slashed_witnesses = slashed_witnesses.iter().cloned().collect();
```
Comment (tmpolaczyk) [inline data_structures/src/data_request.rs]:
```suggestion
        let slashed_witnesses = slashed_witnesses.into_iter().collect();
```

**Comment by tmpolaczyk** [comment]
When #695?

File: data_structures/src/data_request.rs [hunk 2]
```diff
@@ -343,38 +343,39 @@ pub fn create_tally<RT>(
     dr_output: &DataRequestOutput,
     pkh: PublicKeyHash,
     report: &RadonReport<RT>,
-    reveals: Vec<RevealTransaction>,
-    n_commits: usize,
+    reveal_pkhs: Vec<PublicKeyHash>,
+    commit_pkhs: Vec<PublicKeyHash>,
```
Comment (aesedepece) [inline data_structures/src/data_request.rs]: Maybe this is more self-descriptive and less redundant:
```suggestion
    revealers: Vec<PublicKeyHash>,
    commiters: Vec<PublicKeyHash>,
```

File: data_structures/src/data_request.rs [hunk 3]
```diff
@@ -343,38 +343,39 @@ pub fn create_tally<RT>(
...
 ) -> Result<TallyTransaction, failure::Error>
 where
     RT: TypeLike,
 {
     if let Stage::Tally(tally_metadata) = &report.metadata {
         let reveal_reward = dr_output.witness_reward;
+        let n_commits = commit_pkhs.len();
```
Comment (aesedepece) [inline data_structures/src/data_request.rs]: `n` is ambiguous:
```suggestion
        let commits_count = commit_pkhs.len();
```

File: data_structures/src/data_request.rs [hunk 4]
```diff
@@ -343,38 +343,39 @@ pub fn create_tally<RT>(
...
+        let mut slashed_witnesses: HashSet<PublicKeyHash> = commit_pkhs.iter().cloned().collect();
 
         let liars = &tally_metadata.liars;
 
-        if reveals.len() != liars.len() {
+        if reveal_pkhs.len() != liars.len() {
             return Err(TransactionError::MismatchingLiarsNumber {
-                reveals_n: reveals.len(),
+                reveals_n: reveal_pkhs.len(),
```
Comment (aesedepece) [inline data_structures/src/data_request.rs]: `reveal_pkhs.len()` is called twice in a row. Even if there's no performance penalization for it, I think it could use a binding just like you did for `commits_count` aka `n_commits`.

File: data_structures/src/data_request.rs [hunk 5]
```diff
@@ -343,38 +343,39 @@ pub fn create_tally<RT>(
...
 
-        let mut rewarded_witnesses = vec![];
-        let mut outputs: Vec<ValueTransferOutput> = reveals
+        let mut outputs: Vec<ValueTransferOutput> = reveal_pkhs
             .iter()
             .zip(liars.iter())
-            .filter_map(|(reveal, &liar)| {
+            .filter_map(|(&reveal_pkh, &liar)| {
                 // Only reward reveals in consensus
                 if !liar {
```
Comment (aesedepece) [inline data_structures/src/data_request.rs]: We can take this chance for inverting the branches of this decision so as to avoid a negative conditional as per [rule #8](https://www.robertsrulesofcoders.com/).

File: data_structures/src/data_request.rs [hunk 6]
```diff
@@ -343,38 +343,39 @@ pub fn create_tally<RT>(
...
             .into());
         }
 
-        let mut rewarded_witnesses = vec![];
-        let mut outputs: Vec<ValueTransferOutput> = reveals
+        let mut outputs: Vec<ValueTransferOutput> = reveal_pkhs
             .iter()
             .zip(liars.iter())
-            .filter_map(|(reveal, &liar)| {
+            .filter_map(|(&reveal_pkh, &liar)| {
```
Comment (aesedepece) [inline data_structures/src/data_request.rs]: In accordance to previous suggestions:
```suggestion
            .filter_map(|(&revealer, &liar)| {
```

You will see a line down below become super expressive:
```rust
slashed_witnesses.remove(&revealer);
```

File: node/src/actors/chain_manager/mining.rs [hunk 7]
```diff
@@ -494,7 +494,9 @@ impl ChainManager {
                     let min_consensus_ratio =
                         f64::from(dr_state.data_request.min_consensus_percentage) / 100.0;
 
-                    let num_commits = dr_state.info.commits.len();
+                    let commit_pkhs: Vec<PublicKeyHash> =
+                        dr_state.info.commits.keys().cloned().collect();
+                    let num_commits = commit_pkhs.len();
```
Comment (aesedepece) [inline node/src/actors/chain_manager/mining.rs]: Previous naming suggestions apply here too.

File: data_structures/src/data_request.rs [hunk 8]
```diff
@@ -343,48 +343,50 @@ pub fn create_tally<RT>(
...
+    committers: Vec<PublicKeyHash>,
 ) -> Result<TallyTransaction, failure::Error>
 where
     RT: TypeLike,
 {
     if let Stage::Tally(tally_metadata) = &report.metadata {
         let reveal_reward = dr_output.witness_reward;
+        let commits_count = committers.len();
+        let reveals_count = revealers.len();
+        let mut slashed_witnesses: HashSet<PublicKeyHash> = committers.iter().cloned().collect();
```
Comment (aesedepece) [inline data_structures/src/data_request.rs]: Can't `committers` be cloned directly, provided `impl<T: Clone, S: Clone> Clone for HashSet<T, S>`?

File: validations/src/tests.rs [hunk 9]
```diff
@@ -2857,11 +2863,16 @@ fn dr_pool_with_dr_in_tally_stage_no_commits() -> (DataRequestPool, Hash, Public
         DataRequestStage::TALLY
     );
 
-    (dr_pool, dr_pointer, dr_pkh)
+    (dr_pool, dr_pointer, dr_output, dr_pkh)
 }
 
-fn dr_pool_with_dr_in_tally_stage_no_reveals(
-) -> (DataRequestPool, Hash, PublicKeyHash, Vec<PublicKeyHash>) {
+fn dr_pool_with_dr_in_tally_stage_no_reveals() -> (
```
Comment (aesedepece) [inline validations/src/tests.rs]: I think all these tests could use a human friendly description of the setup they are reproducing.

If you think it's also a good idea, I can make suggestions for them (although I will have to discuss with you, as some of them are not evident to me).

Comment (lrubiorod) [reply validations/src/tests.rs]: Should we do in other issue? To do not delay the patch for the testnet

Comment (aesedepece) [reply validations/src/tests.rs]: My concern is that I can't verify the completeness of the tests without fully understanding the setups being tested.

Comment (aesedepece) [reply validations/src/tests.rs]: Awesome comments. Marking as resolved.

File: data_structures/src/data_request.rs (hunk 8 above)
Comment (aesedepece) [reply data_structures/src/data_request.rs]: Ping on this, sorry for being picky ;)
