### PR TITLE
Bridge batch report

### LINKED ISSUE #2046: ReportResult with timestamp assessment
The latest version of the witnet request board provides for two different signatures of the `reportResult` method. The new one has an additional second argument that contains a timestamp, just in case we are on chains without reliable block timestamps. The point of this issue is to explore whether we can leverage that new feature from the bridge or on the contrary polymorphism is not supported by `web3-rust`.

### LINKED ISSUE #2131: Bridge actor dies on panic
```
[2021-11-29T13:26:50Z DEBUG witnet_centralized_ethereum_bridge::actors::eth_poller] Checking new DRs from Ethereum contract...

thread 'main' panicked at 'receipt can't be null after wait for confirmations; qed', /home/witnet/.cargo/registry/src/github.com-1ecc6299db9ec823/web3-0.16.0/src/confirm.rs:88:10

stack backtrace:

   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1321:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: <actix::fut::future::map::Map<Fut,F> as actix::fut::future::ActorFuture<A>>::poll
   6: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
   7: tokio::runtime::task::harness::Harness<T,S>::poll
   8: std::thread::local::LocalKey<T>::with
   9: tokio::task::local::LocalSet::tick
  10: tokio::macros::scoped_tls::ScopedKey<T>::set
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: tokio::macros::scoped_tls::ScopedKey<T>::set
  13: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  14: tokio::runtime::Runtime::block_on
  15: actix_rt::system::SystemRunner::run
  16: witnet_centralized_ethereum_bridge::main

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2021-11-29T13:27:26Z INFO  witnet_centralized_ethereum_bridge::actors::wit_poller] [424] Found possible tally to be reported for dr_tx_hash 78f0c8617124aed361ed488da43396242958d47f31bbc5bfba109f05b120daf2

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MailboxError(Mailbox has closed)', bridges/centralized-ethereum/src/actors/wit_poller.rs:141:30

stack backtrace:

   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <actix::fut::future::then::Then<A,B,F> as actix::fut::future::ActorFuture<Act>>::poll
   5: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
   6: tokio::runtime::task::harness::Harness<T,S>::poll
   7: std::thread::local::LocalKey<T>::with
   8: tokio::task::local::LocalSet::tick
   9: tokio::macros::scoped_tls::ScopedKey<T>::set
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: tokio::macros::scoped_tls::ScopedKey<T>::set
  12: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  13: tokio::runtime::Runtime::block_on
  14: actix_rt::system::SystemRunner::run
  15: witnet_centralized_ethereum_bridge::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### LINKED ISSUE #2163: Bridge: implement and test batch reporting

### PR DESCRIPTION
**Pull request by tmpolaczyk**
Close #2163
Fix #2046
Fix #2131

### CODE REVIEW

File: bridges/centralized-ethereum/src/actors/dr_reporter.rs [hunk 1]
```diff
@@ -10,14 +10,14 @@ use crate::{
 };
 use actix::prelude::*;
 use std::{collections::HashSet, sync::Arc, time::Duration};
+use web3::contract::tokens::Tokenize;
```
Comment (lrubiorod) [inline bridges/centralized-ethereum/src/actors/dr_reporter.rs:13]: fmt

File: bridges/centralized-ethereum/src/actors/dr_reporter.rs [hunk 2]
```diff
@@ -68,12 +68,20 @@ impl DrReporter {
     }
 }
 
-/// Report the result of this data request id to ethereum
+/// Report the result of this data requests to ethereum
```
Comment (lrubiorod) [inline bridges/centralized-ethereum/src/actors/dr_reporter.rs:71]:
```suggestion
/// Report the results of this data requests to ethereum
```

File: bridges/centralized-ethereum/src/actors/dr_reporter.rs [hunk 3]
```diff
@@ -68,12 +68,20 @@ impl DrReporter {
...
+/// Report the result of this data request id to ethereum
+pub struct Report {
     /// Data request id in ethereum
     pub dr_id: DrId,
-    /// Data Request Bytes
-    pub dr_bytes: Bytes,
+    /// Timestamp of the solving commit txs in Witnet. If zero is provided, EVM-timestamp will be used instead
+    pub timestamp: u64,
+    // Data Request Bytes
+    //pub dr_bytes: Bytes,
```
Comment (lrubiorod) [inline bridges/centralized-ethereum/src/actors/dr_reporter.rs:84]: if we are not using, should we remove it?

Comment (tmpolaczyk) [reply bridges/centralized-ethereum/src/actors/dr_reporter.rs:84]: Yes

File: bridges/centralized-ethereum/src/actors/dr_sender.rs [hunk 4]
```diff
@@ -1,3 +1,4 @@
+use crate::actors::dr_reporter::Report;
```
Comment (lrubiorod) [inline bridges/centralized-ethereum/src/actors/dr_sender.rs:1]: fmt

File: bridges/centralized-ethereum/src/actors/wit_poller.rs [hunk 5]
```diff
@@ -1,3 +1,4 @@
+use crate::actors::dr_reporter::Report;
```
Comment (lrubiorod) [inline bridges/centralized-ethereum/src/actors/wit_poller.rs:1]: fmt

File: bridges/centralized-ethereum/src/actors/dr_reporter.rs (hunk 2 above)
Comment (aesedepece) [inline bridges/centralized-ethereum/src/actors/dr_reporter.rs:71]: Even better:
```suggestion
/// Report the results of these data requests to Ethereum
```

File: bridges/centralized-ethereum/src/actors/dr_reporter.rs [hunk 6]
```diff
@@ -88,116 +96,144 @@ impl Handler<DrReporterMsg> for DrReporter {
     type Result = ();
 
     fn handle(&mut self, mut msg: DrReporterMsg, ctx: &mut Self::Context) -> Self::Result {
-        if self.pending_report_result.contains(&msg.dr_id) {
-            // Timeout not elapsed, abort
-            log::debug!(
-                "Request [{}] is already being resolved, ignoring DrReporterMsg",
-                msg.dr_id
-            );
+        // Remove all reports that have already been reported, but the transaction is pending
```
Comment (aesedepece) [inline bridges/centralized-ethereum/src/actors/dr_reporter.rs:99]:
```suggestion
        // Remove all reports that have already been reported, but whose reporting transaction is still pending
```

File: bridges/centralized-ethereum/src/actors/dr_reporter.rs [hunk 7]
```diff
@@ -88,116 +96,144 @@ impl Handler<DrReporterMsg> for DrReporter {
...
+        msg.reports.retain(|report| {
+            if self.pending_report_result.contains(&report.dr_id) {
+                // Timeout not elapsed, abort
```
Comment (aesedepece) [inline bridges/centralized-ethereum/src/actors/dr_reporter.rs:102]:
```suggestion
                // Timeout is not over yet, no action is needed
```

File: bridges/centralized-ethereum/src/actors/dr_reporter.rs [hunk 8]
```diff
@@ -88,116 +96,144 @@ impl Handler<DrReporterMsg> for DrReporter {
...
-                // The request is already resolved, nothing more to do
+            let mut reports = vec![];
+            for report in msg.reports.drain(..) {
+                if let Some(set_dr_info_bridge_msg) =
+                    read_resolved_request_from_contract(report.dr_id, &wrb_contract, eth_account)
+                        .await
+                {
+                    let dr_database_addr = DrDatabase::from_registry();
+                    dr_database_addr.send(set_dr_info_bridge_msg).await.ok();
+                    // The request is already resolved, remove it from list
```
Comment (aesedepece) [inline bridges/centralized-ethereum/src/actors/dr_reporter.rs:149]:
```suggestion
                    // The request was already resolved, we can remove it from the list
```

File: bridges/centralized-ethereum/src/actors/dr_reporter.rs [hunk 9]
```diff
@@ -88,116 +96,144 @@ impl Handler<DrReporterMsg> for DrReporter {
...
                     }
                 }
-                Err(e) => {
-                    log::error!("ReadGasPrice {:?}", e);
+                Ok(Err(e)) => {
+                    // Error in call_with_confirmations
+                    log::error!("reportResultBatch{:?}: {:?}", params_str, e);
+                }
+                Err(_e) => {
+                    // Timeout elapsed
```
Comment (aesedepece) [inline bridges/centralized-ethereum/src/actors/dr_reporter.rs:226]:
```suggestion
                    // Timeout is over
```

File: bridges/centralized-ethereum/src/actors/dr_reporter.rs [hunk 10]
```diff
@@ -88,116 +96,144 @@ impl Handler<DrReporterMsg> for DrReporter {
...
+                    log::warn!("reportResultBatch{:?}: timeout elapsed", params_str);
```
Comment (aesedepece) [inline bridges/centralized-ethereum/src/actors/dr_reporter.rs:227]:
```suggestion
                    log::warn!("reportResultBatch{:?}: timeout is over", params_str);
```

File: bridges/centralized-ethereum/src/actors/dr_reporter.rs [hunk 11]
```diff
@@ -250,3 +286,36 @@ async fn read_resolved_request_from_contract(
...
     None
 }
+
+async fn get_max_gas_price(
+    msg: &DrReporterMsg,
+    wrb_contract: &Contract<Http>,
+    eth_account: H160,
+) -> U256 {
+    // The gas price of the report transaction should be the maximum gas price of any
+    // request
```
Comment (aesedepece) [inline bridges/centralized-ethereum/src/actors/dr_reporter.rs:296]:
```suggestion
    // The gas price of the report transaction should equal the maximum gas price paid
    // by any of the requests being solved here
```

**Review by aesedepece — CHANGES_REQUESTED** [review]

File: bridges/centralized-ethereum/src/actors/dr_reporter.rs [hunk 12]
```diff
@@ -185,45 +185,58 @@ impl Handler<DrReporterMsg> for DrReporter {
                 .collect();
             let verbose = true;
             let params_str = format!("{:?}", (&batch_results, verbose));
```
Comment (tmpolaczyk) [inline bridges/centralized-ethereum/src/actors/dr_reporter.rs:187]: This is wrong, should be calculated inside the for loop

File: bridges/centralized-ethereum/src/actors/dr_reporter.rs [hunk 13]
```diff
@@ -88,116 +96,175 @@ impl Handler<DrReporterMsg> for DrReporter {
...
+            for (batch_results, estimated_gas_limit) in batches {
+                let only_1_batch = batch_results.len() == 1;
+                let receipt = if only_1_batch {
+                    let (dr_id, ts, dr_tx_hash, report_result) =
+                        unwrap_batch(batch_results[0].clone());
+
                     let receipt_fut = wrb_contract.call_with_confirmations(
                         "reportResult",
-                        (msg.dr_id, dr_hash, msg.result),
+                        (dr_id, ts, dr_tx_hash, report_result),
```
Comment (tmpolaczyk) [inline bridges/centralized-ethereum/src/actors/dr_reporter.rs:207]: Maybe this works?

```suggestion
batch_results[0].clone(),
```

Comment (lrubiorod) [reply bridges/centralized-ethereum/src/actors/dr_reporter.rs:207]: at least compile...

Comment (tmpolaczyk) [reply bridges/centralized-ethereum/src/actors/dr_reporter.rs:207]: Unfortunately it didn't work, because when a function has 4 arguments, the web3 library expects a tuple with 4 elements. And batch_results[0] is a Token::Tuple with 4 elements, but that doesn't count as 4 arguments but as 1.

File: bridges/centralized-ethereum/src/actors/dr_reporter.rs [hunk 14]
```diff
@@ -10,14 +10,14 @@ use crate::{
 };
 use actix::prelude::*;
 use std::{collections::HashSet, sync::Arc, time::Duration};
+use web3::ethabi::Token;
```
Comment (lrubiorod) [inline bridges/centralized-ethereum/src/actors/dr_reporter.rs:13]: fmt

File: bridges/centralized-ethereum/src/actors/wit_poller.rs [hunk 15]
```diff
@@ -130,15 +133,58 @@ impl WitPoller {
...
+                                        "error in getBlock call ({}): {:?}",
+                                        dr_block_hash,
+                                        e
+                                    );
+                                    continue;
+                                }
+                            };
+
+                            let block_number = block.block_header.beacon.checkpoint;
+                            // TODO: get constants from somewhere instead of hardcoding them here?
```
Comment (lrubiorod) [inline bridges/centralized-ethereum/src/actors/wit_poller.rs:172]: image
There is a jsonrpc method that returns the consensus constants

**Comment by tmpolaczyk** [comment]
> Do you return the timestamp according to block explorer way (+1 epoch)?

No, because this should be the timestamp of when the commit transaction was created, not the timestamp of the block that includes that transaction.

**Comment by lrubiorod** [comment]
> > Do you return the timestamp according to block explorer way (+1 epoch)?
> 
> No, because this should be the timestamp of when the commit transaction was created, not the timestamp of the block that includes that transaction.

According with a TODO comment in the wit_poller, we are using the timestamp when the request was included, so using the timestamp when the block that includes the data request is included in the blockchain could be nearer to the timestamp when the commit transaction was created, what do you think?

**Review by lrubiorod — APPROVED** [review]

**Review by lrubiorod — APPROVED** [review]
