### PR TITLE
fix(peering): add public address field to fix bucketing problems

### LINKED ISSUE #1055: New bucket bug
I have checked that there are not saving new addresses in new bucket that are different from config file

### PR DESCRIPTION
**Pull request by lrubiorod**
Fix #1055

### CODE REVIEW

File: node/src/actors/sessions_manager/actor.rs [hunk 1]
```diff
@@ -25,7 +25,7 @@ impl Actor for SessionsManager {
 
                 // Set server address, connections limits and handshake timeout
                 act.sessions
-                    .set_server_address(config.connections.server_addr);
+                    .set_server_address(config.connections.public_addr);
```
Comment (tmpolaczyk) [inline node/src/actors/sessions_manager/actor.rs]: Maybe we should rename this method and `self.server_address` into `self.public_address`?

```suggestion
                    .set_public_address(config.connections.public_addr);
```

**Comment by aesedepece** [comment]
It works!

File: node/src/actors/sessions_manager/actor.rs (hunk 1 above)
Comment (aesedepece) [reply node/src/actors/sessions_manager/actor.rs]: Agreed.

File: node/src/actors/session/mod.rs [hunk 2]
```diff
@@ -45,8 +45,8 @@ impl HandshakeFlags {
 
 /// Session representing a TCP connection
 pub struct Session {
-    /// Server socket address (local peer)
-    server_addr: SocketAddr,
+    /// Server public socket address (local peer)
```
Comment (tmpolaczyk) [inline node/src/actors/session/mod.rs]: This comment is not clear enough

```suggestion
    /// Public address of the node (the one used by other peers to connect to ours)
```

File: config/src/config.rs [hunk 3]
```diff
@@ -150,6 +150,9 @@ pub struct Connections {
     /// peers should bind to
     pub server_addr: SocketAddr,
 
+    /// Public address
+    pub public_addr: SocketAddr,
```
Comment (tmpolaczyk) [inline config/src/config.rs]: Does it make sense to make this an `Option`? For people that don't have a public IP.

```suggestion
    pub public_addr: Option<SocketAddr>,
```

Comment (lrubiorod) [reply config/src/config.rs]: They only should have to put the same IP that in server_address

Comment (aesedepece) [reply config/src/config.rs]: > They only should have to put the same IP that in server_address

For it to work, it is true that leaving the default address `0.0.0.0:...` just does the job as you still have to put some IP in the message that is exchanged. 

I am not claiming though that that's ideal in the long term. This is just the option with the lowest impact (it doesn't cause a hard fork as the protobuf schema remains intact).

File: data_structures/src/builders.rs [hunk 4]
```diff
@@ -66,7 +66,7 @@ impl Message {
                 version: PROTOCOL_VERSION,
                 timestamp: get_timestamp(),
                 capabilities: CAPABILITIES,
-                sender_address: to_address(sender_addr),
+                sender_address: sender_addr.map(to_address),
```
Comment (tmpolaczyk) [inline data_structures/src/builders.rs:69]: Maybe we can serialize `None` as `SocketAddr::default()` to avoid that ugly `impl ProtobufConvert`

```suggestion
                sender_address: sender_addr.unwrap_or_default(),
```
