### PR TITLE
fix(node): wait 1 epoch before sending superblock vote

### LINKED ISSUE #1573: Wait for one more epoch to relay superblock votes
We observed a race condition while consutring superblocks. Currently the current flow is:

-> 1.Change epoch
-> 2.Count votes
-> 3.Construct superblock
-> 4.Relay Votes

But if one node does 4 while another node is between 1 and 2, this vote will be considered invalid. If we wait onre more epoch to relay superblock votes this should be solved

### PR DESCRIPTION
**Pull request by tmpolaczyk**
Fix #1573

Also, improved the "Add vote" log line, now it looks like:

```
[2020-09-21T13:04:10Z DEBUG witnet_data_structures::superblock] Add vote: ValidWithSameHash SUPERBLOCK_VOTE twit1fulan0j78dmdfa3gx0779kszj5sc5j35feljv5 #3463: ce1ff0a6b34a1fb0587bebae84a4440240500f08cb1581fce0b1e71b09cc85d7
```

### CODE REVIEW

File: node/src/actors/chain_manager/mod.rs [hunk 1]
```diff
@@ -728,16 +728,22 @@ impl ChainManager {
...
-                            );
-
-                            actix::fut::err(())
-                        }
+                    .map(|res, act, ctx| {
+                        // Broadcast vote one epoch checkpoint later.
+                        // This is used to prevent the race condition described in issue #1573
+                        let checkpoints_period = act.consensus_constants().checkpoints_period;
+                        ctx.run_later(
+                            Duration::from_seconds(u64::from(checkpoints_period)),
```
Comment (lrubiorod) [inline node/src/actors/chain_manager/mod.rs:736]:
```suggestion
                            Duration::from_secs(u64::from(checkpoints_period)),
```

**Review by lrubiorod — APPROVED** [review]

**Review by clbartoli — APPROVED** [review]

**Review by girazoki — APPROVED** [review]
