### PR TITLE
feat(node): add ready state and fix EpochManager bugs to ease genesis…

### LINKED ISSUE #1116: Verify that delayed chain bootstraping works as intended
Last chain bootstrapping (T7.1) was the first time we made a rehearsal for a delayed chain bootstrapping.

When the checkpoint zero arrived (at UTC midnight on March 21), not every node was able to fulfill a successful bootstrapping of its local chain, judging by the errors reported by some community members on Discord.

We should investigate what the specific errors happened so that we can make sure that future bootstrapping events go smoother.

### PR DESCRIPTION
**Pull request by lrubiorod**
… event

Close #1116

### CODE REVIEW

File: node/src/actors/chain_manager/handlers.rs [hunk 1]
```diff
@@ -126,129 +115,144 @@ impl Handler<EpochNotification<EveryEpochPayload>> for ChainManager {
...
-                        .sorted_by_key(|(_key, (_block_candidate, vrf_proof))| *vrf_proof)
-                    {
-                        let block_pkh = &block_candidate.block_sig.public_key.pkh();
-                        let reputation = rep_engine.trs().get(block_pkh);
-
-                        if let Some((chosen_key, chosen_reputation, chosen_vrf_proof, _, _)) =
-                            chosen_candidate
+            StateMachine::Synced | StateMachine::Ready => {
+                if self.sm_state == StateMachine::Synced && current_epoch > 0 {
+                    // We only reach Ready state after genesis event
```
Comment (tmpolaczyk) [inline node/src/actors/chain_manager/handlers.rs:120]: What's the issue with being in Ready state in epoch 0?

Comment (lrubiorod) [reply node/src/actors/chain_manager/handlers.rs:120]: that you will be able to mine, and the epoch 0 is for the genesis block

Comment (tmpolaczyk) [reply node/src/actors/chain_manager/handlers.rs:120]: Then we can move this check to `mining.rs`, as

    if self.sm_state != StateMachine::Ready || current_epoch == 0

**Comment by aesedepece** [comment]
The state machine would then be modeled like this:
```
WaitingConsensus +---> Syncing +---> Synced +---> Live
       ^                  +            +            +
       |                  |            |            |
       +------------------+            |            |
       |                               |            |
       +-------------------------------+            |
       |                                            |
       +--------------------------------------------+
```

File: node/src/actors/chain_manager/actor.rs [hunk 2]
```diff
@@ -252,7 +249,11 @@ impl ChainManager {
                         warn!("Checkpoint zero is in the future ({:?}). Delaying chain bootstrapping until then.", date);
                         // Subscribe to first epoch
                         epoch_manager_addr
-                            .do_send(Subscribe::to_epoch(0, chain_manager_addr, EpochPayload))
+                            .do_send(Subscribe::to_epoch(0, chain_manager_addr.clone(), EveryEpochPayload));
```
Comment (tmpolaczyk) [inline node/src/actors/chain_manager/actor.rs:252]: Is going to trigger the same handler as `Subscribe::to_all`? If so, it will be executed twice for epoch 0. Or does `Subscribe::to_all` only send messages when the epoch is >= 1?

Comment (lrubiorod) [reply node/src/actors/chain_manager/actor.rs:252]: The second

Comment (lrubiorod) [reply node/src/actors/chain_manager/actor.rs:252]: Or not? Mmm...

File: node/src/actors/chain_manager/mod.rs [hunk 3]
```diff
@@ -94,8 +94,8 @@ pub enum ChainManagerError {
     #[fail(display = "ChainManager is not ready yet")]
     ChainNotReady,
     /// The node is not in Synced state
-    #[fail(display = "The node is not yet synchronized")]
-    NotSynced,
+    #[fail(display = "The node is not yet ready")]
+    NotReady,
```
[the remark this answers is not in the document]
Comment (lrubiorod) [reply node/src/actors/chain_manager/mod.rs:98]: why should be so important to keep the context? I mean, the ChainManager handler should not allow processing requests for json_rpc until the node is fully synced and ready to work, it doesnt matter what request would be.

File: node/src/actors/chain_manager/mod.rs [hunk 4]
```diff
@@ -528,9 +530,9 @@ impl ChainManager {
         );
         // Ignore AddTransaction when not in Synced state
         match self.sm_state {
-            StateMachine::Synced => {}
+            StateMachine::Ready => {}
             _ => {
-                return Box::new(actix::fut::err(ChainManagerError::NotSynced.into()));
+                return Box::new(actix::fut::err(ChainManagerError::NotReady.into()));
```
[the remark this answers is not in the document]
Comment (lrubiorod) [reply node/src/actors/chain_manager/mod.rs:535]: In this case, we dont want to manage all the transactions that we receive until we can handle them, that it is in Live time

File: node/src/actors/chain_manager/mod.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (aesedepece) [reply node/src/actors/chain_manager/mod.rs:98]: It's only for debugging purposes. If some day I find this error message, I'd love to know where specifically something odd happened.

File: node/src/actors/epoch_manager/mod.rs [hunk 5]
```diff
@@ -146,17 +146,24 @@ impl EpochManager {
...
+                current_epoch
+                    .checked_add(1)
+                    .ok_or(EpochManagerError::Overflow)?,
+            )?;
 
-        duration_between_timestamps((now_secs, now_nanos), (next_checkpoint, 0))
-            .ok_or(EpochManagerError::Overflow)
+            duration_between_timestamps((now_secs, now_nanos), (next_checkpoint, 0))
+                .ok_or(EpochManagerError::Overflow)
+        }
```
[the remark this answers is not in the document]
Comment (aesedepece) [reply node/src/actors/epoch_manager/mod.rs:166]: I don't think this is resolved :stuck_out_tongue:

File: node/src/actors/sessions_manager/mod.rs [hunk 6]
```diff
@@ -178,6 +178,10 @@ impl SessionsManager {
         // Get EpochManager address from registry
         let epoch_manager_addr = EpochManager::from_registry();
 
+        if self.current_epoch == 0 {
+            epoch_manager_addr.do_send(Subscribe::to_epoch(0, ctx.address(), ()));
+        }
```
Comment (aesedepece) [inline node/src/actors/sessions_manager/mod.rs:183]: This can use a comment.

File: reputation/src/ars.rs [hunk 7]
```diff
@@ -152,6 +152,9 @@ where
             self.push_activity(identities);
             self.last_update = new_time;
 
+            Ok(())
+        } else if new_time == 0 {
+            // In the epoch 0 there are not reputation updating
```
Comment (aesedepece) [inline reputation/src/ars.rs:157]:
```suggestion
            // In the epoch 0 (genesis block) there must be no reputation update
```

File: node/src/actors/chain_manager/actor.rs (hunk 2 above)
Comment (lrubiorod) [reply node/src/actors/chain_manager/actor.rs:252]: Yes, it was redundant. I removed the redundant parts, thanks!!

File: node/src/actors/chain_manager/mining.rs [hunk 8]
```diff
@@ -53,9 +53,9 @@ impl ChainManager {
             return;
         }
 
-        // We only want to mine in Synced state
-        if self.sm_state != StateMachine::Synced {
-            log::debug!("Not mining because node is not synced");
+        // We only want to mine in Ready state
+        if self.sm_state != StateMachine::Live {
+            log::debug!("Not mining because node is not in Ready State");
```
Comment (tmpolaczyk) [inline node/src/actors/chain_manager/mining.rs:58]: Search "Ready" and replace by "Live"?

```suggestion
            log::debug!("Not mining because node is not in Live State");
```

File: node/src/actors/epoch_manager/mod.rs [hunk 9]
```diff
@@ -146,14 +146,21 @@ impl EpochManager {
...
-        // Get timestamp for the start of next checkpoint
-        let next_checkpoint = self.epoch_timestamp(
-            current_epoch
-                .checked_add(1)
-                .ok_or(EpochManagerError::Overflow)?,
-        )?;
+        let current_epoch_res = self.epoch_at(now_secs);
+
+        let next_checkpoint =
+            if let Err(EpochManagerError::CheckpointZeroInTheFuture(zero)) = current_epoch_res {
```
Comment (tmpolaczyk) [inline node/src/actors/epoch_manager/mod.rs:152]: I think this would be more clear as a `match`

Comment (aesedepece) [reply node/src/actors/epoch_manager/mod.rs:152]: I agree, but I was unsure of whether `clippy` would complain about using match for a simple two-clause conditional. If `clippy` is OK with it, it's a :+1: from me.

Comment (lrubiorod) [reply node/src/actors/epoch_manager/mod.rs:152]: clippy approves

**Comment by aesedepece** [comment]
I NEED THIS!!!
```
                               
██╗     ██╗██╗   ██╗███████╗██╗
██║     ██║██║   ██║██╔════╝██║
██║     ██║██║   ██║█████╗  ██║
██║     ██║╚██╗ ██╔╝██╔══╝  ╚═╝
███████╗██║ ╚████╔╝ ███████╗██╗
╚══════╝╚═╝  ╚═══╝  ╚══════╝╚═╝
```
