### PR TITLE
fix(wallet): re-implement index transactions

### LINKED ISSUE #956: Re-implement index transactions
Re-implement the index transaction business logic under the following assumptions:

- `createVtt` request does not persist the transactions
- `createVtt` request does not modify the UTXO set
- `createVtt` API method will return a signed transaction
- Sheikah will use `sendTransaction` API method to trigger a broadcast of the attached transaction towards the node.

Therefore, the index transaction logic will be (for now) completely stateless regarding any pending transaction or blocked/used UTXO. UTXOs and balances will be updated once transactions are indexed every new block.

Things to address in future issues:

- When Sheikah confirms a transaction (using `sendTransaction`), the wallet should mark the used UTXOs as `used` (attaching a `timestamp`) and the transaction as `pending`.
- When Sheikah requests the transaction list, the wallet will return also the pending transactions.
- When Sheikah requests the balance (or is notified), the wallet will return also the `available balance` and the `unconfirmed balance` (taking into account the pending UTXOs and transactions).
- Wallet will implement some logic to support the recovery of `blocked` UTXOs in case a pending transaction is never included in the chain.

### PR DESCRIPTION
**Pull request by mariocao**
This PR:

- re-implements the index transactions business logic
- adds key to DBKeyNotFound error

Closes #956

### CODE REVIEW

File: wallet/src/model.rs [hunk 1]
```diff
@@ -69,8 +69,7 @@ where
 #[derive(Debug, Serialize)]
 pub struct Transaction {
     pub hex_hash: String,
-    pub value: u64,
-    pub entry: TransactionEntry,
+    pub value: i64,
```
Comment (tmpolaczyk) [inline wallet/src/model.rs]: Why is this now a `i64`? A `Transaction` value cannot be negative

File: wallet/src/repository/wallet/mod.rs [hunk 2]
```diff
@@ -315,38 +316,19 @@ where
         txns: &[types::VTTransactionBody],
     ) -> Result<()> {
         // FIXME: Handle multiple accounts when indexing transactions
```
Comment (tmpolaczyk) [inline wallet/src/repository/wallet/mod.rs]: Is multi-account support still a goal? If not, remove this comment.

File: wallet/src/repository/wallet/mod.rs [hunk 3]
```diff
@@ -315,38 +316,19 @@ where
...
-                            txn_hash: hash.clone(),
-                            output_index: index as u32,
-                        };
-                        self._index_transaction_output(&mut state, &hash, out_ptr, &output, block)?;
-                    }
-                }
+            if self
+                .db
+                .get_opt::<_, u32>(&keys::transactions_index(&hash))?
+                .is_none()
```
Comment (tmpolaczyk) [inline wallet/src/repository/wallet/mod.rs]: Add comments about why are we checking that this value is `None`, and explain what happens when the value is `Some` (it is ignored?)

File: wallet/src/repository/wallet/mod.rs [hunk 4]
```diff
@@ -648,116 +570,96 @@ where
...
-
-            self.db.write(batch)?;
-
-            state.transaction_next_id = txn_next_id;
-            state.balance = new_balance;
-            state.utxo_set.remove(&out_ptr);
+        let mut db_utxo_set: model::UtxoSet = self
+            .db
+            .get(&keys::account_utxo_set(account))
+            .unwrap_or_default();
```
Comment (tmpolaczyk) [inline wallet/src/repository/wallet/mod.rs]: `unwrap_or_default` ignores any errors and creates a new variable. Maybe it would be better to use `get_opt(...)?.unwrap_or_default()`, so errors are handled with `?`.

File: wallet/src/model.rs (hunk 1 above)
Comment (mariocao) [reply wallet/src/model.rs]: We got rid of the type `Entry` which was `Debit` or `Credit`, which now can be derived by Sheikah from its sign.

File: wallet/src/repository/wallet/mod.rs [hunk 5]
```diff
@@ -648,116 +570,96 @@ where
...
+
+        let mut input_amount: u64 = 0;
+        for input in txn.inputs.iter() {
+            let out_ptr: model::OutPtr = input.output_pointer().into();
+
+            if let Some(model::KeyBalance { amount, .. }) = state.utxo_set.get(&out_ptr).cloned() {
```
Comment (tmpolaczyk) [inline wallet/src/repository/wallet/mod.rs]: `map.get()` followed with `map.remove()` can be simplified as just `map.remove()`, because remove returns the value, if any.

```suggestion
            if let Some(model::KeyBalance { amount, .. }) = state.utxo_set.remove(&out_ptr) {
```

File: wallet/src/repository/wallet/mod.rs [hunk 6]
```diff
@@ -648,116 +570,96 @@ where
...
-            batch.put(keys::transaction_next_id(account), txn_next_id)?;
-            batch.put(keys::transactions_index(txn_hash), txn_id)?;
-            batch.put(keys::transaction_hash(account, txn_id), txn_hash)?;
-
-            self.db.write(batch)?;
-
-            state.transaction_next_id = txn_next_id;
-            state.balance = new_balance;
-            state.utxo_set.remove(&out_ptr);
+        let mut db_utxo_set: model::UtxoSet = self
```
Comment (tmpolaczyk) [inline wallet/src/repository/wallet/mod.rs]: What's the difference between `db_utxo_set` and `state.utxo_set`?

File: wallet/src/repository/wallet/mod.rs (hunk 4 above)
Comment (mariocao) [reply wallet/src/repository/wallet/mod.rs]: It was something from the inherited code. The `unwrap_or_default` is used when the UXTO set was never initialized and an empty one is created.

File: wallet/src/repository/wallet/mod.rs (hunk 6 above)
Comment (mariocao) [reply wallet/src/repository/wallet/mod.rs]: State is memory, DB is persisted in the database. Please take into account that many things you are commenting are not decisions of @lrubiorod and I.

Comment (mariocao) [reply wallet/src/repository/wallet/mod.rs]: use `wallet --help` :rofl:

File: wallet/src/repository/wallet/mod.rs [hunk 7]
```diff
@@ -648,116 +570,96 @@ where
...
+                    amount: output.value,
+                };
+
+                let out_ptr = model::OutPtr {
+                    txn_hash: Vec::from(txn_hash),
+                    output_index: index as u32,
+                };
+
+                match db_utxo_set.insert(out_ptr.clone(), key_balance.clone()) {
+                    Some(x) if x == key_balance => {}
```
Comment (tmpolaczyk) [inline wallet/src/repository/wallet/mod.rs]: When can this branch happen? When indexing the same transaction twice? Or when some transaction does not change the account balance?

File: wallet/src/repository/wallet/mod.rs [hunk 8]
```diff
@@ -648,116 +570,96 @@ where
...
+        }
 
-            batch.put(&keys::transaction_value(account, txn_id), amount)?;
-            batch.put(
-                keys::transaction_entry(account, txn_id),
-                model::TransactionEntry::Credit,
-            )?;
+        let txn_balance = (output_amount as i128)
+            .checked_sub(input_amount as i128)
+            .ok_or_else(|| Error::TransactionBalanceUnderflow)?;
```
Comment (tmpolaczyk) [inline wallet/src/repository/wallet/mod.rs]: If `output_amount` is a `u64` and `input_amount` is a `u64`, this error can never happen. But you can leave it to prevent future errors.

File: wallet/src/repository/wallet/mod.rs [hunk 9]
```diff
@@ -648,116 +570,96 @@ where
...
+
+        let txn_balance =
+            i64::try_from(txn_balance).map_err(|_| Error::TransactionValueOverflow)?;
```
Comment (tmpolaczyk) [inline wallet/src/repository/wallet/mod.rs]: Shouldn't this be transaction balance?

```suggestion
            i64::try_from(txn_balance).map_err(|_| Error::TransactionBalanceOverflow)?;
```

File: wallet/src/repository/wallet/mod.rs [hunk 10]
```diff
@@ -648,116 +570,96 @@ where
...
+            let new_balance = if txn_balance > 0 {
+                state
+                    .balance
+                    .checked_add(txn_balance.abs() as u64)
+                    .ok_or_else(|| Error::TransactionBalanceOverflow)?
+            } else {
+                state
+                    .balance
+                    .checked_sub(txn_balance.abs() as u64)
+                    .ok_or_else(|| Error::TransactionBalanceUnderflow)?
```
Comment (tmpolaczyk) [inline wallet/src/repository/wallet/mod.rs]: I don't think this is a good error name. Is this the error that appears when trying to create a transaction with more value than the account balance? If so, it needs to be more descriptive. In the node that error is called `NoMoney`, and provides context about the account balance and the transaction value.

If this error should never happen (and only appears when the storage is corrupted or something), then I'm fine with renaming it as:

```suggestion
                    .ok_or_else(|| Error::TransactionBalanceNegative)?
```

File: wallet/src/model.rs (hunk 1 above)
Comment (tmpolaczyk) [reply wallet/src/model.rs]: Then this `value` is the change of the account balance? Add comment :)

File: wallet/src/repository/wallet/mod.rs (hunk 3 above)
Comment (mariocao) [reply wallet/src/repository/wallet/mod.rs]: If `Some` we will log a warning because the transaction is already in our database. This should never happen. :man_facepalming:

File: wallet/src/repository/wallet/tests/mod.rs [hunk 11]
```diff
@@ -793,7 +752,7 @@ fn test_index_transaction_vtt_created_by_wallet() {
 
     let a_block = factories::BlockInfo::default().create();
     let our_address = wallet.gen_external_address(None).unwrap();
-    let their_address = wallet.gen_external_address(None).unwrap();
+    let their_pkh = PublicKeyHash::from_str("wit1mx47n6zp4y574a3xvjt90kefc7lggvgw0v39mf").unwrap();
```
Comment (tmpolaczyk) [inline wallet/src/repository/wallet/tests/mod.rs]: Why is this?

Comment (mariocao) [reply wallet/src/repository/wallet/tests/mod.rs]: I changed it to `factories::pkh()`. The problem before was that the generated `pkh` is derived from the same wallet, so that the `index_transactions` was not working as the test was intended.
