### PR TITLE
Miscellaneous fixes

### LINKED ISSUE #650: Modify MintTransaction
Modify MintTransaction outputs field:

outputs: Vec<ValueTransferOutput> -> output: ValueTransferOutput

### PR DESCRIPTION
**Pull request by tmpolaczyk**
These are some changes that I made while writing the tests in #678 

- Fix #650: mint transaction should only have one output
- Fix VRF false positives
- Fix DataRequestEligibilityClaim using wrong epoch in proof message
- Fix DataRequest fee calculation
- Add validation for VRF Proof PKH == signature PKH

### CODE REVIEW

File: validations/src/validations.rs [hunk 1]
```diff
@@ -566,17 +575,13 @@ pub fn validate_block_transactions(
     let ta_hash_merkle_root = ta_mt.root();
 
     // Validate mint
-    validate_mint_transaction(
-        &block.txns.mint,
-        total_fee,
-        block_reward(block.block_header.beacon.checkpoint),
-    )?;
+    validate_mint_transaction(&block.txns.mint, total_fee, beacon.checkpoint)?;
```
Comment (lrubiorod) [inline validations/src/validations.rs]: change variable name beacon for block_beacon

File: data_structures/src/error.rs [hunk 2]
```diff
@@ -60,7 +60,7 @@ pub enum TransactionError {
         dr_value, witnesses
     )]
     InvalidDataRequestValue { dr_value: i64, witnesses: i64 },
-    #[fail(display = "Data Request witnesses number is not enough")]
+    #[fail(display = "There needs to be at least 1 witness in a data request")]
```
Comment (lrubiorod) [inline data_structures/src/error.rs]: It is not defined that 1 witness is the minimum
