### PR TITLE
fix(bridge): ignore rust-web3 error when eth_syncing returns true

### LINKED ISSUE #2141: Web3 lib refuses connection to unsynced providers
When trying to connect to Etherereum node, `eth_syncing` is first RPC to be called. If `true` is returned, the centralized bridge will crash saying:

```
[2021-12-20T14:25:41Z ERROR witnet_centralized_ethereum_bridge] Failed to connect to ethereum node: Decoder error: Error("expected object or `false`, got `true`", line: 0, column: 0) thread 'main' panicked at 'ethereum node not running: "Decoder error: Error(\"expected object or `false`, got `true`\", line: 0, column: 0)"', bridges/centralized-ethereum/src/main.rs:110:18

stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
   3: witnet_centralized_ethereum_bridge::run::{{closure}}
   4: tokio::macros::scoped_tls::ScopedKey<T>::set
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: tokio::macros::scoped_tls::ScopedKey<T>::set
   7: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
   8: tokio::runtime::Runtime::block_on
   9: witnet_centralized_ethereum_bridge::main

```

### PR DESCRIPTION
**Pull request by tmpolaczyk**
And show warnings if the ethereum node is syncing

Fix #2141

### CODE REVIEW

File: bridges/centralized-ethereum/src/lib.rs [hunk 1]
```diff
@@ -83,15 +83,35 @@ pub async fn check_ethereum_node_running(eth_client_url: &str) -> Result<(), Str
...
+                }
+            }
 
             Ok(())
         }
         Err(e) => {
-            log::error!("Failed to connect to ethereum node: {}", e);
+            match e {
+                web3::Error::Decoder(error_msg)
+                    if error_msg == "expected object or `false`, got `true`" =>
```
Comment (guidiaz) [inline bridges/centralized-ethereum/src/lib.rs:100]: if error_msg.contains("expected object or `false`, got `true`") =>

**Review by guidiaz — APPROVED** [review]
